name: Codesonar GitHub Demo
on:
  pull_request:
env:
  PROJECT_NAME: ${{ github.event.repository.name }}
jobs:
  analyze:
  # perm required to solve "Resource not accessible by integration" warning when trying to upload SARIF
    permissions: write-all
    runs-on:
    # VM-Ubuntu is my laptop
      - VM-Ubuntu
    # MrHermeling is Marks basement machine
    # - MrHermeling
    env:
      CODESONAR: /home/daniel/share_data/codesonar/codesonar-8.2p0/codesonar/bin/codesonar
      # JAVA_HOME needed to execute Kotlin Detekt tool
      #JAVA_HOME: /opt/codesonar/win32-fetcher/jdk-11-x86_64-pc-linux-gnu
      #JAVAC: /opt/codesonar/win32-fetcher/jdk-11-x86_64-pc-linux-gnu/bin/javac
      #JAVA: /opt/codesonar/win32-fetcher/jdk-11-x86_64-pc-linux-gnu/bin/java
      #CS_JAVA_SCAN: /opt/codesonar/codesonar/bin/cs-java-scan
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASS: "${{ secrets.CSONAR_HUB_PASS }}"
      #HUB_CERT: "${{ secrets.ROB_HUB_CERT }}"
      #HUB_KEY: "${{ secrets.ROB_HUB_KEY }}"
      CSONAR_HUB_URL: "http://0.0.0.0:7340"
      #CSPYTHON: /opt/codesonar/codesonar/bin/cspython
      #CSO_GITHUB: /opt/codesonar-github
      #GITHUB_CAFILE: ".github/github.cert.pem"
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
      
    container:
    # this container includes analysis support for C/C++, Java, Python, JS family, Kotlin
      image: ghcr.io/rdaultongt/csonar_github:toolchain-codesonar8.3p0
      credentials:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASS }}
    timeout-minutes: 360
    steps:
     - uses: actions/checkout@v3
     - name: setup credentials files
       run: |
          echo "$HUB_CERT" > hubCert
          echo "$HUB_KEY" > hubKey
          echo "testing" > test 
     - name: build C/C++
       run: >
          "$CODESONAR" analyze
          -clean
          -auth password
          -hubuser "$CSONAR_HUB_USER"
          -project "$PROJECT_NAME"
          "$PROJECT_NAME"
          "$CSONAR_HUB_URL"
          gcc -c -I. demo.cpp second.cpp
     - name: Fail Action if there are new warnings
       run: newCount=`"$CODESONAR" dump_warnings.py --project-file "$PROJECT_NAME" -auth certificate -hubuser "$CSONAR_HUB_USER" -hubcert ./hubCert -hubkey ./hubKey --hub "$CSONAR_HUB_URL" --visible-warnings new | wc`
     - name: Pull Analysis Results from CodeSonar Hub
       run: >
          "$CODESONAR" dump_warnings.py
          -o warnings.sarif
          --hub "$CSONAR_HUB_URL"
          -auth certificate -hubuser "$CSONAR_HUB_USER" -hubcert ./hubCert -hubkey ./hubKey
          --project-file "$PROJECT_NAME"
          --sarif
          --src-root "$GITHUB_WORKSPACE"
          --visible-warnings excludeSourcelessArtifacts
          -t 7200
     - name: Push Analysis Results to GitHub
       uses: github/codeql-action/upload-sarif@v3
       with:
          sarif_file: warnings.sarif
     - name: Push Summary Report
       if: ${{ github.event.pull_request }}
       run: >
          "$CSPYTHON" "$CSO_GITHUB/sarif_summary.py"
          warnings.sarif
          "$CSONAR_HUB_URL"
          "$PROJECT_NAME"
          | "$CSPYTHON" "$CSO_GITHUB/push_github_pr_comment.py"
          --api-url "$GITHUB_API_URL"
          --cafile "$GITHUB_CAFILE"
          "$GITHUB_REPOSITORY"
          "$PULL_REQUEST_ID"
          GH_TOKEN
     - name: generate PDF report
       run: |
          AID=`"$CODESONAR" analysis_id.py "$PROJECT_NAME"`
          "$CODESONAR" get -auth certificate -hubuser "$CSONAR_HUB_USER" -hubcert ./hubCert -hubkey ./hubKey "$CSONAR_HUB_URL/report/aid-$AID-analysis.pdf?size=A4&orientation=landscape"
     - name: upload SARIF and PDF Report to GitHub
       uses: actions/upload-artifact@v4
       with:
         name: Upload Artifacts
         path: |
           warnings.sarif
           **/*.pdf
